
default:
		./client.py agentx.ccs.neu.edu -p 27993 000582102
		./client.py agentx.ccs.neu.edu -p 27993 000568047

ssl:
	./client.py agentx.ccs.neu.edu -p 27994 -s 000582102
	./client.py agentx.ccs.neu.edu -p 27994 -s 000568047

